---
- name: wired network configuration
  template:
    src: systemd-networkd-config-wired.j2
    dest: /etc/systemd/network/20-wired.network
    mode: '0644'
  when: net_iface is defined

- name: bridge configuration
  block:
    - name: bridge interface
      template:
        src: systemd-networkd-bridge.netdev.j2
        dest: /etc/systemd/network/"{{ bridge }}".netdev

    - name: bind ethernet to bridge
      template:
        src: systemd-networkd-bridge-bind.network.j2
        dest: /etc/systemd/network/"{{ bridge }}"-bind.network

    - name: bridge network
      template:
        src: systemd-networkd-bridge-network.j2
        dest: /etc/systemd/networkd/"{{ bridge }}".network
  when: bridge is defined

- name: enable systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: true

- name: enable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: true
