---
- name: packages for grub
  block:
    - name: install grub
      pacman:
        name: grub
        state: present

    - name: install efibootmgr
      pacman:
        name: efibootmgr
        state: present
      when: grub_firmware == 'efi'

- name: grub installation (bios)
  block:
    - name: install grub
      command: grub-install --target=i386-pc "{{ grub_disk }}"
  when: grub_firmware == 'bios'

- name: grub installation (efi)
  block:
    - name: install grub
      command: grub-install --target=x86_64-efi --efi-directory="{{ grub_efi_dir }}" --bootloader-id=GRUB
  when: grub_firmware == 'efi'

- name: grub configuration file
  command: grub-mkconfig -o /boot/grub/grub.cfg
